steps:
   - name: 'node'
    entrypoint: 'npm'
    args: ['install', '@dataform/cli']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['cp', 'environment_${_ENV}.json', 'environment.json','&&','echo','{
    "projectId": "${PROJECT_ID}",
    "location": "US"
}
','>', '.df-credentials.json']
 - name: 'node'
    entrypoint: 'npm'
    args: ['dataform', 'run']
 
substitutions:
    _ENV:'dev'