steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install', '@dataform/cli']
  - name: 'bash'
    args: ['-c', 'cp environment_$ENV.json environment.json','&&','echo','-c','{
    "projectId": $PROJECT_ID,
    "location": "US"} > .df-credentials.json']
    env:
      - 'ENV=${_ENV}'
      - 'PROJECT_ID=$PROJECT_ID'
  - name: 'node'
    entrypoint: 'npm'
    args: ['dataform', 'run']
  